name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Generate Android project
        run: flutter create --platforms android --org vn.minhcanhmobile .

      - name: Install dependencies
        run: flutter pub get

      - name: Check source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build release APK
        run: flutter build apk --release

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: MinhCanhMobileV3-APK
          path: build/app/outputs/flutter-apk/app-release.apk
